# Generated by scripts/homebrew-formula.sh in hzrbasaran/rustClean.
class Rustclean < Formula
  desc "Terminal disk usage analyzer and cleaner"
  homepage "https://github.com/hzrbasaran/rustClean"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.4.0/rustclean-v0.4.0-aarch64-apple-darwin.tar.gz"
      sha256 "550cc1513787078b37be20126946609b248438e8ddc96ca814b2a83f67886397"
    end
    on_intel do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.4.0/rustclean-v0.4.0-x86_64-apple-darwin.tar.gz"
      sha256 "a715f71020c2b293fd615e66310827cf799139bd95f861bf873b0bed922ee61e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.4.0/rustclean-v0.4.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ae1bf037c351ae7c339398276033324e8d3249eb89b355ac87c5287f45989ded"
    end
  end

  def install
    bin.install "rustclean"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rustclean --version")
  end
end
