# Generated by scripts/homebrew-formula.sh in hzrbasaran/rustClean.
class Rustclean < Formula
  desc "Terminal disk usage analyzer and cleaner"
  homepage "https://github.com/hzrbasaran/rustClean"
  version "0.1.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.1.0/rustclean-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "6f65610d6dd22d8b53b31cdfb2a5b1a39dec1b658ad37a411a6fded6a28e7c13"
    end
    on_intel do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.1.0/rustclean-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "912def009f77c84e8053256641e16c33a9ed40c75ad823d3ec532c422b8ad218"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.1.0/rustclean-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "347fa122133d2b789e8e7dd091c3e2d49390b1b6582f80ff499539ce36f5ce08"
    end
  end

  def install
    bin.install "rustclean"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rustclean --version")
  end
end
