# Generated by scripts/homebrew-formula.sh in hzrbasaran/rustClean.
class Rustclean < Formula
  desc "Terminal disk usage analyzer and cleaner"
  homepage "https://github.com/hzrbasaran/rustClean"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.5.0/rustclean-v0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "58a9fbe00bd9335e1066267bc8f2545651e95ddc72f5d1c38893d24d2f8392a7"
    end
    on_intel do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.5.0/rustclean-v0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "04d17c244c146e2ce26eb99ad98b098e91ba3aa82f67558c2d833250237c1494"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hzrbasaran/rustClean/releases/download/v0.5.0/rustclean-v0.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "23657abf7fb3187052dae711feada6599a96dcaa09f358d921f42292b1df5327"
    end
  end

  def install
    bin.install "rustclean"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rustclean --version")
  end
end
